name: recursive_reasoning.legacy.transformers_baseline@Model_ACTV2
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

halt_exploration_prob: 0.1
halt_max_steps: 1 # 16 for ACT, 1 for no ACT

H_cycles: 1  # kept for compatibility
H_layers: 10 

hidden_size: 768  
num_heads: 12
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope